### ISSUE TITLE
Add support for Svelte

### ISSUE THREAD

**Issue by DreamTexX** [SanderRonde/prettier-plugin-sort-imports#12]
Hey, is it possible to add support for svelte files? Currently it does not seem to have any effect on scripts inside components.

**Comment by SanderRonde** [comment]
I gave it a try but unfortunately failed to get it work (see the https://github.com/SanderRonde/prettier-plugin-sort-imports/tree/svelte branch). The reason is the same as [this issue](https://github.com/prettier/prettier/issues/12807), namely that the plugin system in prettier is kind of a mess and interactions between plugins are not very predictable. If plugin A overrides a thing and plugin B overrides a thing then weird things like where in the alphabet the plugin name occurs determine which one of them will work and which one won't.

In this case it appears that since svelte has declared itself as a parser, a "clean" import of that package is done whenever a new svelte parser is created. This means that any overrides my plugin applies (overriding the regular formatting function) are thrown away, meaning it doesn't work.

I'd love to give you some "but hopefully I can implement it when that issue is fixed" thing to look forward to but given that the issue has had no comment from a maintainer in 2 years I'm not too optimistic on that happening any time soon.

So I think for now I'll close this as a won't fix, but I'm definitely open to the idea and would love to implement it once that's possible :)
